name: Podcast Mobile CD

on:
  push:
    branches: [ main, maui/perf ]
    paths:
      - 'src/Mobile/**'
      - '**/*build.props'      
      - '.github/workflows/podcast-mobile-cd.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ROOT_PATH: src/Mobile/
  CSPROJ_PATH: src/Mobile/Microsoft.NetConf2021.Maui.csproj
  ENCRYPTED_KEYSTORE_PATH: android-keystore-test.jks.gpg # RELATIVE TO github.workspace
  KEYSTORE_PATH: android-keystore-test.keystore # RELATIVE TO github.workspace
  ARTIFACTS_PATH: artifacts # RELATIVE TO github.workspace

jobs:
  windows-build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Install MAUI Workloads
        run: |
          dotnet workload install maui --source https://api.nuget.org/v3/index.json

      # BUILD
      - name: Restore dependencies
        shell: pwsh
        run: |
          dotnet restore ${{ env.CSPROJ_PATH }}


      #You need your csrpoj.targetframeworks net6.0-windows10.0.19041 without Condition="$([MSBuild]::IsOSPlatform......
      - name: Build Maui WinUI project
        shell: pwsh
        run: |
          dotnet publish ${{ env.CSPROJ_PATH }} -c Release -f net6.0-windows10.0.19041

      #POST-BUILD
      - name: Create artifacts folder
        shell: pwsh
        run: |
           cd ${{ github.workspace }}
           mkdir ${{ env.ARTIFACTS_PATH }}

      - name: Copy Windows bin
        shell: pwsh 
        run: |
           Get-Childitem –Path ${{ github.workspace }} -Include *.msix -File -Recurse | Copy-Item -Destination ${{ env.ARTIFACTS_PATH }}

      - name: Publish build artifacts
        uses: actions/upload-artifact@v2
        with:     
          name: "WinUI .NET MAUI artifacts" 
          path: "${{ env.ARTIFACTS_PATH }}/*"
          if-no-files-found: error
          retention-days: 90

  macos-build-android-macos-ios:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - name: Install MAUI Workloads
        run: |
          dotnet workload install ios --ignore-failed-sources
          dotnet workload install maccatalyst --ignore-failed-sources
          dotnet workload install maui --source https://api.nuget.org/v3/index.json

      # BUILD
      - name: Restore dependencies
        run: dotnet restore ${{ env.CSPROJ_PATH }}

      - name: Build MAUI IOS
        run: dotnet publish ${{ env.CSPROJ_PATH }} -c Release -f net6.0-ios --no-restore

      - name: Build MAUI MacCatalyst
        run: dotnet build src/MauiBeach/MauiBeach.csproj -c Release -f net6.0-maccatalyst --no-restore

      #TODO Build IOS AND MacOS      
      #POST-BUILD
      - name: Create artifacts folder
        shell: pwsh
        run: |
           cd ${{ github.workspace }}
           mkdir ${{ env.ARTIFACTS_PATH }}

      #TODO add filter and only upload signed artifacts      
      - name: Publish build artifacts
        uses: actions/upload-artifact@v2
        with:     
          name: "Podcast Mobile artifacts" 
          path: "${{ env.ARTIFACTS_PATH }}/*"
          if-no-files-found: error
          retention-days: 90
